chore: Added pipenv and setup.cfg
opensource-nepal/django-nepali pull request #11
Opened 2023-06-30 15:57 UTC by aj3sh

- Removed old requirements file
- Added pipenv file
- Added setup.cfg file
- Removed setup.py file
- Added contributing file and updated Readme file for it
- Update github actions for installing dependencies from pipenv

2023-07-10 03:52 UTC, sugat009 requested changes

2023-07-10 03:52 UTC, sugat009 commented on .github/workflows/python-package.yml
> +          pipenv run pytest --cov=django_nepali/ --no-cov-on-fail
@aj3sh this seems to be pending

2023-07-10 15:34 UTC, aj3sh commented on .github/workflows/python-package.yml
> +          pipenv run pytest --cov=django_nepali/ --no-cov-on-fail
Updated

2023-07-10 15:36 UTC, sugat009 approved these changes

2023-07-11 02:01 UTC, theoctober19th requested changes

2023-07-11 12:26 UTC, aj3sh commented on .github/workflows/python-package.yml
>            python -m pip install flake8
Earlier, Flake8 wasn't in our dev dependencies. We are using it as a part of a CI check, as you can see there is a CI step for Flake8 linting. 
But we can update it now. Thanks for the suggestion.

2023-07-11 15:05 UTC, aj3sh commented on .github/workflows/python-package.yml
>            python -m pip install flake8
Updated

2023-07-11 15:05 UTC, aj3sh commented on Makefile
> +install:
Updated

2023-07-11 15:05 UTC, aj3sh commented on CONTRIBUTING.md
> +A [.editorconfig](./editorconfig) is available to maintain the coding style. Besides, your code will automatically gets formatted if you have install the pre-commit hook.
Updated

2023-07-11 15:08 UTC, sugat009 approved these changes

2023-07-13 02:55 UTC, theoctober19th approved these changes
LGTM

2023-07-13 03:22 UTC, merged